const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.join(__dirname,'..');const validation=fs.readFileSync(path.join(root,'public/order-validation.js'),'utf8');
function fixture(){const fields=new Map();const document={addEventListener(){},querySelectorAll(){return []},getElementById(id){if(!fields.has(id))fields.set(id,{hidden:id==='trackingCard',querySelector(){return null},addEventListener(){},classList:{add(){},remove(){},toggle(){}},style:{},setAttribute(k,v){this[k]=v},scrollIntoView(){},value:'',innerHTML:''});return fields.get(id)}};const c={document,console,AbortController,addEventListener(){},Date:class extends Date{constructor(...args){super(...(args.length?args:['2026-10-03T12:00:00Z']))}},location:{origin:'https://example.test',reload(){}},localStorage:{getItem(){return ''},setItem(){},removeItem(){}},setTimeout(){},clearTimeout(){},setInterval(){return 1},clearInterval(){},fetch:async()=>({ok:true,json:async()=>({categories:[],products:[],order:{status:'accepted',order_items:[]}})})};c.window=c;vm.createContext(c);vm.runInContext(validation,c);vm.runInContext(fs.readFileSync(path.join(root,'public/guest-catalog-view.js'),'utf8'),c);vm.runInContext([...fs.readFileSync(path.join(root,'public/index.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n'),c);return c;}
test('phone validation requires Belarus prefix and nine digits',()=>{const v=fixture().OrderValidation;for(const s of ['+375291234567','+375 (29) 123-45-67'])assert.equal(v.normalizePhone(s),'+375291234567');for(const s of ['291234567','+7291234567','+375','+3752912345678','+375abc291234567'])assert.equal(v.normalizePhone(s),'');});
test('comments filter whole words without blocking ordinary food requests',()=>{const v=fixture().OrderValidation;for(const s of ['Без лука, пожалуйста','Страхуем доставку','Хлеб и соль','ребенок ждет'])assert.equal(v.hasProfanity(s),false,s);for(const s of ['БЛЯТЬ!','сука','пиздец','fuck','хуй'])assert.equal(v.hasProfanity(s),true,s);assert.ok(v.validate({phone:'+375291234567',items:[{comment:'блять'}]}));});
test('website does not expose customer order tracking',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.doesNotMatch(html,/id="trackingLink"|id="trackingCard"|prilavok_tracking_token|startTrackingPolling|renderTracking|toggleTracking/);});
test('paste full number in fixed prefix field',()=>{const c=fixture(),input={value:'+375 (29) 123-45-67'};c.formatPhoneInput(input);assert.equal(input.value,'291234567');});
test('checkout rejects bad phone and profanity before database access',async()=>{const {mountOwnerRoutes,ownerBotAuthorized}=await import('../owner-auth.js');const {createPhoneVerificationService}=await import('../phone-verification.js');const {createCheckoutService}=await import('../checkout-service.js');const routes={};const app={use(){},get(){},put(){},patch(){},delete(){},post(path,handler){routes[path]=handler},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};const c={console,express,mountOwnerRoutes,ownerBotAuthorized,createPhoneVerificationService,createCheckoutService,createTelegramOrderAlerts:()=>({notifyNewOrder:async()=>({}),configure:async()=>({ok:true})}),createLivePosReports:()=>({access:async()=>({ok:true}),request:async()=>({ok:true,report:{}}),submit:()=>true}),createAvailabilityService:()=>({}),cors:()=>{},process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},createClient:()=>({from(){throw Error('Database must not be accessed')}}),setInterval(){},randomUUID:()=>''};vm.createContext(c);vm.runInContext(validation,c);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),c);for(const body of [{phone:'+72912345678',comment:''},{phone:'+375291234567',comment:'блять'}]){const res={status(n){this.code=n;return this},json(value){this.body=value;return this}};await routes['/api/checkout']({protocol:'https',get:()=> 'example.test',body:{...body,customerName:'Тест',items:[{productId:'1',quantity:1}]}},res);assert.equal(res.code,400);assert.ok(res.body.error);}});

test('product detail updates quantity without reopening the screen',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/function refreshProductDetail\(id\)\{if\(activeProductId!==id\)return/);assert.doesNotMatch(html,/function refreshProductDetail\(id\)\{openProductDetail\(id\)\}/);assert.match(html,/refreshProductDetail\(id\);animateCartAdd\(d\)/);});
test('product detail uses transition based visibility instead of display toggling',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/\.product-detail\{[^}]*visibility:hidden;opacity:0/);assert.match(html,/\.product-detail\.is-open\{[^}]*visibility:visible;opacity:1/);assert.doesNotMatch(html,/productDetail'\)\.style\.display='block'/);});

test('Phone confirmation always rejects forged callbacks regardless of Owner rollout flag',async()=>{
 const {mountOwnerRoutes,ownerBotAuthorized}=await import('../owner-auth.js');
 const routes={};let confirmations=0;
 const app={use(){},get(){},put(){},patch(){},delete(){},post(p,h){routes[p]=h},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};
 const context={console,express,setInterval(){},cors:()=>{},mountOwnerRoutes,ownerBotAuthorized,process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test',OWNER_AUTH_ENABLED:'true',OWNER_BOT_SHARED_SECRET:'s'.repeat(43)}},createClient:()=>({}),createPhoneVerificationService:()=>({confirm:async()=>{confirmations++;return {ok:true}}}),createTelegramOrderAlerts:()=>({notifyNewOrder:async()=>({}),configure:async()=>({ok:true})}),createLivePosReports:()=>({access:async()=>({ok:true}),request:async()=>({ok:true,report:{}}),submit:()=>true}),createAvailabilityService:()=>({}),createCheckoutService:()=>({finalizeByVerificationToken:async()=>({ok:true})})};
 vm.createContext(context);vm.runInContext(validation,context);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),context);
 for(const flag of [undefined,'false','true']){context.process.env.OWNER_AUTH_ENABLED=flag;for(const secret of [undefined,'wrong','s'.repeat(43)]){const res={status(n){this.code=n;return this},json(value){this.body=value;return this}};await routes['/api/phone-verification/:token/confirm']({header:()=>secret,body:{phone:'+375291234567',telegramUserId:123},params:{token:'token'}},res);assert.equal(res.code||200,secret==='s'.repeat(43)?200:403);}
 }
 assert.equal(confirmations,3);
});

test('demand status is preloaded and refresh lifecycle stays production-safe',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/Обычная загруженность/);assert.match(html,/Ваш заказ постараются приготовить быстро/);assert.match(html,/Повышенная загруженность/);assert.match(html,/Заказ может готовиться дольше обычного/);assert.match(html,/Статус загруженности временно недоступен/);assert.match(html,/async function preloadDemandStatus\(\)/);assert.match(html,/void preloadDemandStatus\(\);loadMenu\(\)/);assert.doesNotMatch(html,/window\.__DEMAND_LAST=null/);assert.match(html,/const DEMAND_REFRESH_MS=25000/);assert.match(html,/demandRefreshTimer=setTimeout\(\(\)=>scheduleDemandStatus\(\{quiet:true\}\),DEMAND_REFRESH_MS\)/);assert.match(html,/demandController\?\.abort\(\).*demandSeq\+\+/s);assert.match(html,/if\(seq!==demandSeq\)return/);assert.match(html,/visibilitychange/);});

test('demand status failure is informational and does not gate checkout',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');const submit=html.slice(html.indexOf('async function submitOrder()'),html.indexOf('function statusInfo'));assert.doesNotMatch(submit,/DEMAND_LAST|demandController|scheduleDemandStatus|available/);assert.match(submit,/fetch\(API\+'\/api\/checkout'/);assert.match(submit,/location\.href=j\.telegramUrl/);assert.doesNotMatch(submit,/trackingToken|localStorage/);});

test('demand UI contains no retired ETA naming',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/id="demandCard"/);assert.match(html,/class="demand-card/);assert.doesNotMatch(html,/etaCard|eta-card|eta-title|eta-time|eta-note/);assert.match(html,/\/api\/demand\/status/);});

test('website enforces server availability on cards, cart refresh and checkout',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/function productLimit\(p\)/);assert.match(html,/Нет в наличии/);assert.match(html,/current>=limit/);assert.match(html,/refreshMenuAvailability\(\{announce:true\}\)/);assert.match(html,/Проверяем остатки/);assert.match(html,/available_quantity/);});
test('confirmed checkout triggers the backend POS Telegram alert only for a newly created order',()=>{const server=fs.readFileSync(path.join(root,'server.js'),'utf8');const route=server.slice(server.indexOf('app.post("/api/phone-verification/:token/confirm"'),server.indexOf('app.post("/api/media/upload"'));assert.match(route,/finalized\?\.ok && finalized\.duplicate !== true/);assert.match(route,/telegramOrderAlerts\.notifyNewOrder\(\)/);assert.ok(route.indexOf('finalizeByVerificationToken')<route.indexOf('notifyNewOrder'));});
test('owner live report routes require bot or device authentication and use the active SSE client',()=>{const server=fs.readFileSync(path.join(root,'server.js'),'utf8');assert.match(server,/app\.post\("\/api\/owner\/live-report"/);assert.match(server,/ownerBotAuthorized\(req\.header\("x-owner-bot-secret"/);assert.match(server,/livePosReports\.request\(req\.body\?\.telegramId, deliverLiveReportRequest\)/);assert.match(server,/app\.post\("\/api\/device\/live-report\/:requestId"/);assert.match(server,/const device = await requireDevice\(req, res\)/);assert.match(server,/livePosReports\.submit\(device\.id/);});
test('guest pages share full-width shell and one animated sold-out treatment',()=>{const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),shell=fs.readFileSync(path.join(root,'public/guest-shell.css'),'utf8');assert.match(order,/<link rel="stylesheet" href="\/guest-shell\.css\?v=roulette-20261010-3">/);assert.match(menu,/<link rel="stylesheet" href="\/guest-shell\.css\?v=roulette-20261010-3">/);assert.ok(order.indexOf('<header class="site-top"')<order.indexOf('<div class="wrap">'));assert.ok(menu.indexOf('<header class="top"')<menu.indexOf('<div class="shell">'));assert.match(shell,/\.site-top,\.top\{[^}]*width:100%/);assert.match(shell,/\.sold-out-layer::before\{[^}]*animation:soldOutSweep/);assert.match(shell,/@media\(prefers-reduced-motion:reduce\)/);assert.doesNotMatch(order,/Сегодня закончилось/);assert.doesNotMatch(menu,/Сегодня закончилось/);assert.doesNotMatch(order,/<div class="food-bg"/);assert.doesNotMatch(menu,/<div class="food-bg"/);assert.match(menu,/function productAvailable\(p\)/);});

test('guest branding and product controls use shared visual tokens',()=>{const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),shell=fs.readFileSync(path.join(root,'public/guest-shell.css'),'utf8');assert.match(order,/<title>Проект<\/title>/);assert.match(menu,/<title>Проект<\/title>/);assert.match(shell,/--guest-control-radius:999px/);assert.match(shell,/--guest-card-radius:24px/);assert.match(shell,/\.site-top \.brand,\.top \.brand/);assert.match(shell,/\.add,\.unavailable\{[^}]*min-height:42px/);assert.match(shell,/\.product-wrap \.unavailable\{margin-top:12px/);});

test('product roulette is shared, category-aware and excludes unavailable products',()=>{const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),roulette=fs.readFileSync(path.join(root,'public/guest-roulette.js'),'utf8'),shell=fs.readFileSync(path.join(root,'public/guest-shell.css'),'utf8');for(const html of [order,menu]){assert.match(html,/id="rouletteLaunch"/);assert.match(html,/<script src="\/guest-roulette\.js\?v=roulette-20261010-3"><\/script>/);assert.match(html,/GuestRoulette\?\.mount/)}assert.match(roulette,/options\.isAvailable\(product\)/);assert.match(roulette,/String\(product\.category_id\)===String\(categoryId\)/);assert.match(roulette,/crypto\?\.getRandomValues/);assert.match(roulette,/Открыть товар/);assert.match(roulette,/frameId=requestAnimationFrame\(tick\)/);assert.doesNotMatch(roulette,/cycleTimer|finishTimer|setInterval/);assert.doesNotMatch(roulette,/Рулетка блюд|Рулетка крутится/);assert.match(shell,/\.roulette-select-wrap::after/);assert.match(shell,/\.cartbar::after\{[^}]*height:calc\(120px \+ env\(safe-area-inset-bottom\)\)/);assert.doesNotThrow(()=>new Function(roulette));});

test('online menu and online ordering use separate product visibility channels',()=>{
 const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),server=fs.readFileSync(path.join(root,'server.js'),'utf8');
 assert.match(order,/fetch\(API\+'\/api\/menu'\+suffix/);assert.match(menu,/fetch\('\/api\/menu'\+suffix/);
 assert.match(server,/visible_in_menu: p\.visibleInOnlineMenu !== false/);assert.match(server,/menuSurface \? "visible_in_menu" : "available_online"/);
 assert.match(server,/missingOnlineMenuColumn/);assert.match(server,/withoutOnlineMenuColumn/);
 assert.match(server,/available_online: c\.availableOnline !== false/);assert.match(server,/visible_in_menu: c\.visibleInOnlineMenu !== false/);
});

test('guest catalog cache is bounded and stock is forced fresh at checkout boundaries',()=>{
 const order=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),menu=fs.readFileSync(path.join(root,'public/menu/index.html'),'utf8'),server=fs.readFileSync(path.join(root,'server.js'),'utf8');
 for(const html of [order,menu])assert.match(html,/<script src="\/guest-menu-cache\.js"><\/script>/);
 assert.match(order,/MENU_CACHE_FRESH_MS=7\*24\*60\*60\*1000/);assert.match(menu,/MENU_CACHE_FRESH_MS=7\*24\*60\*60\*1000/);
 assert.match(order,/fetch\(API\+'\/api\/menu\/availability',\{cache:'no-store'\}\)/);assert.match(order,/byExternalId/);
 assert.match(order,/catalog_revision/);assert.match(menu,/catalog_revision/);assert.match(order,/revision=''/);assert.match(menu,/revision=''/);
 assert.match(server,/public, max-age=3600, stale-while-revalidate=86400/);assert.match(server,/filePath\.endsWith\("\.html"\).*no-cache/s);
});

test('catalog and image cache use revision based invalidation for a seven day lifetime',()=>{
 const server=fs.readFileSync(path.join(root,'server.js'),'utf8'),cache=fs.readFileSync(path.join(root,'public/guest-menu-cache.js'),'utf8'),railway=fs.readFileSync(path.join(root,'railway.toml'),'utf8'),ready=fs.readFileSync(path.join(root,'ready-server.js'),'utf8');
 assert.match(cache,/MAX_AGE_MS=7\*24\*60\*60\*1000/);assert.match(server,/advanceCatalogRevision\(\)/);assert.match(server,/max-age=604800, immutable/);
 assert.match(server,/createHash\("sha256"\).*digest\("hex"\)/);assert.match(server,/\?v=\$\{imageVersion\}/);assert.match(server,/"cache-control": "max-age=604800"/);
 assert.match(railway,/sleepApplication = true/);assert.match(ready,/isSiteSleepWindow\(\)/);assert.match(server,/event: sleeping/);
});

test('availability refresh endpoint returns only the compact stock payload without caching',async()=>{
 const routes={},app={use(){},get(path,handler){routes[path]=handler},put(){},patch(){},delete(){},post(){},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};
 const context={console,express,cors:()=>{},mountOwnerRoutes(){},ownerBotAuthorized(){return true},createPhoneVerificationService:()=>({}),createCheckoutService:()=>({}),createTelegramOrderAlerts:()=>({notifyNewOrder:async()=>({}),configure:async()=>({ok:true})}),createLivePosReports:()=>({access:async()=>({ok:true}),request:async()=>({ok:true,report:{}}),submit:()=>true}),createAvailabilityService:()=>({list:async()=>[{externalId:'pizza',quantity:2},{externalId:'water',quantity:null}]}),calculateLoyaltyTransition(){},loyaltyIdempotencyKey(){},validateLoyaltyAllocation(){},randomUUID:()=>'',process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},createClient:()=>({}),setInterval(){}};
 vm.createContext(context);vm.runInContext(validation,context);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),context);
 const headers={};const response={setHeader(name,value){headers[name]=value},json(value){this.body=value;return this},status(value){this.code=value;return this}};await routes['/api/menu/availability']({},response);
 assert.equal(headers['Cache-Control'],'no-store');assert.match(response.body.catalog_revision,/^boot-/);assert.deepEqual(JSON.parse(JSON.stringify(response.body.items)),[{external_id:'pizza',availability_known:true,available_quantity:2},{external_id:'water',availability_known:true,available_quantity:null}]);
});

test('menu endpoint selects the requested visibility column',async()=>{
 const routes={},filters=[];
 const app={use(){},get(path,handler){routes[path]=handler},put(){},patch(){},delete(){},post(){},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};
 const query=table=>{const q={select(){return q},eq(key,value){filters.push({table,key,value});return q},order(){return q},then(resolve){resolve({data:[],error:null})}};return q};
 const context={console,express,cors:()=>{},mountOwnerRoutes(){},ownerBotAuthorized(){return true},createPhoneVerificationService:()=>({}),createCheckoutService:()=>({}),createTelegramOrderAlerts:()=>({notifyNewOrder:async()=>({}),configure:async()=>({ok:true})}),createLivePosReports:()=>({access:async()=>({ok:true}),request:async()=>({ok:true,report:{}}),submit:()=>true}),createAvailabilityService:()=>({attachToProducts:async products=>products}),calculateLoyaltyTransition(){},loyaltyIdempotencyKey(){},validateLoyaltyAllocation(){},randomUUID:()=>'',process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},createClient:()=>({from:query}),setInterval(){}};
 vm.createContext(context);vm.runInContext(validation,context);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),context);
 const cacheHeaders=[];const response={setHeader(name,value){if(name==='Cache-Control')cacheHeaders.push(value)},json(value){this.body=value;return this},status(value){this.code=value;return this}};
 await routes['/api/menu']({query:{}},response);await routes['/api/menu']({query:{surface:'menu'}},response);
 assert.deepEqual(filters.filter(row=>row.table==='products'&&row.key!=='is_active').map(row=>row.key),['available_online','visible_in_menu']);
 assert.deepEqual(filters.filter(row=>row.table==='categories'&&row.key!=='is_active').map(row=>row.key),['available_online','visible_in_menu']);
 assert.deepEqual(cacheHeaders,['private, max-age=120','public, max-age=1800']);
});

test('menu endpoint removes products whose category is hidden on the requested surface',async()=>{
 const routes={};const app={use(){},get(path,handler){routes[path]=handler},put(){},patch(){},delete(){},post(){},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};
 const query=table=>{const q={select(){return q},eq(){return q},order(){return q},then(resolve){resolve({data:table==='categories'?[{id:'visible',name:'Видимая'}]:table==='products'?[{id:'shown',category_id:'visible'},{id:'hidden',category_id:'hidden'}]:[],error:null})}};return q};
 const context={console,express,cors:()=>{},mountOwnerRoutes(){},ownerBotAuthorized(){return true},createPhoneVerificationService:()=>({}),createCheckoutService:()=>({}),createTelegramOrderAlerts:()=>({notifyNewOrder:async()=>({}),configure:async()=>({ok:true})}),createLivePosReports:()=>({access:async()=>({ok:true}),request:async()=>({ok:true,report:{}}),submit:()=>true}),createAvailabilityService:()=>({attachToProducts:async products=>products}),calculateLoyaltyTransition(){},loyaltyIdempotencyKey(){},validateLoyaltyAllocation(){},randomUUID:()=>'',process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},createClient:()=>({from:query}),setInterval(){}};
 vm.createContext(context);vm.runInContext(validation,context);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),context);
 const response={json(value){this.body=value;return this},status(value){this.code=value;return this}};await routes['/api/menu']({query:{}},response);
 assert.deepEqual(response.body.products.map(product=>product.id),['shown']);assert.deepEqual(response.body.categories.map(category=>category.id),['visible']);
});

 test('open ordering tab disables checkout at 22:30 without navigation',()=>{
 const c=fixture();let reloaded=false;
 c.location.reload=()=>{reloaded=true};
 c.Date=class extends Date{constructor(){super('2026-10-03T19:29:59Z')}};
 assert.equal(c.orderingOpenNow(),true);
 c.Date=class extends Date{constructor(){super('2026-10-03T19:30:00Z')}};
 assert.equal(c.orderingOpenNow(),false);
 c.applyOrderingState();assert.equal(reloaded,false);assert.equal(c.document.getElementById('submitBtn').disabled,true);
});
