const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.join(__dirname,'..');const validation=fs.readFileSync(path.join(root,'public/order-validation.js'),'utf8');
function fixture(){const fields=new Map();const document={addEventListener(){},querySelectorAll(){return []},getElementById(id){if(!fields.has(id))fields.set(id,{hidden:id==='trackingCard',querySelector(){return null},addEventListener(){},classList:{add(){},remove(){},toggle(){}},style:{},setAttribute(k,v){this[k]=v},scrollIntoView(){},value:'',innerHTML:''});return fields.get(id)}};const c={document,console,addEventListener(){},location:{origin:'https://example.test'},localStorage:{getItem(){return ''},setItem(){},removeItem(){}},setTimeout(){},clearTimeout(){},setInterval(){return 1},clearInterval(){},fetch:async()=>({ok:true,json:async()=>({categories:[],products:[],order:{status:'accepted',order_items:[]}})})};c.window=c;vm.createContext(c);vm.runInContext(validation,c);vm.runInContext([...fs.readFileSync(path.join(root,'public/index.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n'),c);return c;}
test('phone validation requires Belarus prefix and nine digits',()=>{const v=fixture().OrderValidation;for(const s of ['+375291234567','+375 (29) 123-45-67'])assert.equal(v.normalizePhone(s),'+375291234567');for(const s of ['291234567','+7291234567','+375','+3752912345678','+375abc291234567'])assert.equal(v.normalizePhone(s),'');});
test('comments filter whole words without blocking ordinary food requests',()=>{const v=fixture().OrderValidation;for(const s of ['Без лука, пожалуйста','Страхуем доставку','Хлеб и соль','ребенок ждет'])assert.equal(v.hasProfanity(s),false,s);for(const s of ['БЛЯТЬ!','сука','пиздец','fuck','хуй'])assert.equal(v.hasProfanity(s),true,s);assert.ok(v.validate({phone:'+375291234567',items:[{comment:'блять'}]}));});
test('tracking stays collapsed after background render and toggles',()=>{const c=fixture(),card=c.document.getElementById('trackingCard');c.renderTracking({status:'accepted',order_items:[]});assert.equal(card.hidden,true);assert.match(card.innerHTML,/Заказ подтверждён/);assert.match(card.innerHTML,/✓/);assert.doesNotMatch(card.innerHTML,/status-dot|В работе/);c.toggleTracking();assert.equal(card.hidden,false);c.toggleTracking();assert.equal(card.hidden,true);assert.equal(c.document.getElementById('trackingLink')['aria-expanded'],'false');});
test('new order never gets a confirmation checkmark',()=>{const c=fixture();c.renderTracking({status:'new'});const html=c.document.getElementById('trackingCard').innerHTML;assert.match(html,/Ожидает подтверждения/);assert.doesNotMatch(html,/✓/);});
test('paste full number in fixed prefix field',()=>{const c=fixture(),input={value:'+375 (29) 123-45-67'};c.formatPhoneInput(input);assert.equal(input.value,'291234567');});
test('checkout rejects bad phone and profanity before database access',async()=>{const {mountOwnerRoutes,ownerBotAuthorized}=await import('../owner-auth.js');const {createPhoneVerificationService}=await import('../phone-verification.js');const {createCheckoutService}=await import('../checkout-service.js');const routes={};const app={use(){},get(){},patch(){},post(path,handler){routes[path]=handler},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};const c={console,express,mountOwnerRoutes,ownerBotAuthorized,createPhoneVerificationService,createCheckoutService,cors:()=>{},process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},createClient:()=>({from(){throw Error('Database must not be accessed')}}),setInterval(){},randomUUID:()=>''};vm.createContext(c);vm.runInContext(validation,c);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),c);for(const body of [{phone:'+72912345678',comment:''},{phone:'+375291234567',comment:'блять'}]){const res={status(n){this.code=n;return this},json(value){this.body=value;return this}};await routes['/api/checkout']({protocol:'https',get:()=> 'example.test',body:{...body,customerName:'Тест',items:[{productId:'1',quantity:1}]}},res);assert.equal(res.code,400);assert.ok(res.body.error);}});

test('product detail updates quantity without reopening the screen',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/function refreshProductDetail\(id\)\{if\(activeProductId!==id\)return/);assert.doesNotMatch(html,/function refreshProductDetail\(id\)\{openProductDetail\(id\)\}/);assert.match(html,/refreshProductDetail\(id\);animateCartAdd\(d\)/);});
test('product detail uses transition based visibility instead of display toggling',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');assert.match(html,/\.product-detail\{[^}]*visibility:hidden;opacity:0/);assert.match(html,/\.product-detail\.is-open\{[^}]*visibility:visible;opacity:1/);assert.doesNotMatch(html,/productDetail'\)\.style\.display='block'/);});

test('Owner rollout also protects legacy phone confirmation from a forged callback',async()=>{
 const {mountOwnerRoutes,ownerBotAuthorized}=await import('../owner-auth.js');
 const routes={};let confirmations=0;
 const app={use(){},get(){},patch(){},post(p,h){routes[p]=h},listen(){}};const express=()=>app;express.json=()=>{};express.static=()=>{};
 const context={console,express,setInterval(){},cors:()=>{},mountOwnerRoutes,ownerBotAuthorized,process:{env:{SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test',OWNER_AUTH_ENABLED:'true',OWNER_BOT_SHARED_SECRET:'s'.repeat(43)}},createClient:()=>({}),createPhoneVerificationService:()=>({confirm:async()=>{confirmations++;return {ok:true}}}),createCheckoutService:()=>({finalizeByVerificationToken:async()=>({ok:true})})};
 vm.createContext(context);vm.runInContext(validation,context);vm.runInContext(fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/^import .*;\n/gm,''),context);
 for(const secret of [undefined,'wrong','s'.repeat(43)]){const res={status(n){this.code=n;return this},json(value){this.body=value;return this}};await routes['/api/phone-verification/:token/confirm']({header:()=>secret,body:{phone:'+375291234567',telegramUserId:123},params:{token:'token'}},res);assert.equal(res.code||200,secret==='s'.repeat(43)?200:403);}
 assert.equal(confirmations,1);
});
